# Great Nigeria Library Foundation - Development Docker Compose Override
# Use this for local development with hot reloading and debugging capabilities
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  foundation-db:
    # Development database settings
    environment:
      POSTGRES_DB: great_nigeria_foundation_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5434:5432"  # Different port for dev
    volumes:
      - foundation_db_dev_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/dev-seed.sql:/docker-entrypoint-initdb.d/02-dev-seed.sql:ro
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_duration_statement=0
      -c shared_preload_libraries=pg_stat_statements
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  foundation-redis:
    # Development Redis settings
    command: >
      redis-server
      --appendonly no
      --save ""
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --loglevel verbose
    ports:
      - "6381:6379"  # Different port for dev
    volumes:
      - foundation_redis_dev_data:/data
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

  foundation-app:
    # Development application settings
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    image: great-nigeria-foundation:dev
    environment:
      # Development-specific environment
      ENVIRONMENT: development
      LOG_LEVEL: debug
      GIN_MODE: debug
      
      # Database connection for dev
      DB_HOST: foundation-db
      DB_DATABASE: great_nigeria_foundation_dev
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_password
      
      # Development JWT secret (not secure - for dev only)
      JWT_SECRET: dev-jwt-secret-not-for-production
      
      # Enable development features
      ENABLE_PPROF: true
      ENABLE_DEBUG_ROUTES: true
      ENABLE_CORS_ALL: true
      
      # Hot reload settings
      AIR_ENABLED: true
    ports:
      - "8081:8080"  # Different port for dev
      - "6060:6060"  # pprof debugging port
    volumes:
      # Mount source code for hot reloading
      - ./backend:/app/backend:ro
      - ./main.go:/app/main.go:ro
      - ./go.mod:/app/go.mod:ro
      - ./go.sum:/app/go.sum:ro
      # Development uploads and logs
      - ./dev-uploads:/app/uploads
      - ./dev-logs:/app/logs
      # Development configuration
      - ./config/dev.yaml:/app/config.yaml:ro
    command: >
      sh -c "
        if [ -f /app/air ]; then
          /app/air -c /app/.air.toml
        else
          /app/foundation-app
        fi
      "
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Development database admin tool
  foundation-adminer:
    image: adminer:4.8.1
    container_name: great-nigeria-foundation-adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: foundation-db
      ADMINER_DESIGN: pepa-linha
    networks:
      - foundation-network
    restart: unless-stopped
    profiles:
      - dev-tools

  # Development Redis admin tool
  foundation-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: great-nigeria-foundation-redis-commander
    ports:
      - "8083:8081"
    environment:
      REDIS_HOSTS: local:foundation-redis:6379
      REDIS_PASSWORD: ""
    networks:
      - foundation-network
    restart: unless-stopped
    profiles:
      - dev-tools

  # Development mail catcher
  foundation-mailhog:
    image: mailhog/mailhog:latest
    container_name: great-nigeria-foundation-mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - foundation-network
    restart: unless-stopped
    profiles:
      - dev-tools

volumes:
  foundation_db_dev_data:
    driver: local
  foundation_redis_dev_data:
    driver: local
