services:
  # PostgreSQL Database for Foundation
  foundation-db:
    image: postgres:13-alpine
    container_name: great-nigeria-foundation-db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-great_nigeria_foundation}
      POSTGRES_USER: ${DB_USERNAME:-foundation_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-foundation_pass}
    ports:
      - "${DB_EXTERNAL_PORT:-5433}:5432"
    volumes:
      - foundation_db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - foundation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-foundation_user} -d ${DB_DATABASE:-great_nigeria_foundation}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for Foundation (Sessions, Cache)
  foundation-redis:
    image: redis:6-alpine
    container_name: great-nigeria-foundation-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    ports:
      - "${REDIS_EXTERNAL_PORT:-6380}:6379"
    volumes:
      - foundation_redis_data:/data
    networks:
      - foundation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Foundation Application
  foundation-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: great-nigeria-foundation-app
    environment:
      # Database Configuration
      DB_HOST: foundation-db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-foundation_user}
      DB_PASSWORD: ${DB_PASSWORD:-foundation_pass}
      DB_DATABASE: ${DB_DATABASE:-great_nigeria_foundation}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}

      # Redis Configuration
      REDIS_HOST: foundation-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DATABASE: ${REDIS_DATABASE:-0}

      # Server Configuration
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
      SERVER_PORT: ${SERVER_PORT:-8080}
      ENVIRONMENT: ${ENVIRONMENT:-development}

      # Auth Configuration
      JWT_SECRET: ${JWT_SECRET:-foundation-jwt-secret-key-change-in-production}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION:-15m}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION:-168h}

      # Email Configuration
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      FROM_EMAIL: ${FROM_EMAIL:-noreply@greatnigeria.com}
      FROM_NAME: ${FROM_NAME:-Great Nigeria Library}

      # OAuth Configuration
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL:-http://localhost:8080/auth/google/callback}

      # Storage Configuration
      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      STORAGE_LOCAL_PATH: ${STORAGE_LOCAL_PATH:-./uploads}
      S3_REGION: ${S3_REGION:-}
      S3_BUCKET: ${S3_BUCKET:-}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-}

      # Logging Configuration
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FORMAT: ${LOG_FORMAT:-json}
      LOG_OUTPUT: ${LOG_OUTPUT:-stdout}
      LOG_FILE: ${LOG_FILE:-app.log}
    ports:
      - "${SERVER_EXTERNAL_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      foundation-db:
        condition: service_healthy
      foundation-redis:
        condition: service_healthy
    networks:
      - foundation-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${SERVER_PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  foundation_db_data:
    driver: local
  foundation_redis_data:
    driver: local

networks:
  foundation-network:
    driver: bridge
